name: memee_admin
description: A Grocery app admin panel
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.11.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  excel: ^3.0.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  get_it: ^7.2.0
  go_router: ^6.0.0
  image_picker: ^1.0.4
  logger: ^2.0.2+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
