// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2OofbM1L50yBUTqeEwWEUdyMqFPv7zN4',
    appId: '1:163218598684:web:31b13552ceb6c44b2928d9',
    messagingSenderId: '163218598684',
    projectId: 'memee-dev-d104d',
    authDomain: 'memee-dev-d104d.firebaseapp.com',
    storageBucket: 'memee-dev-d104d.appspot.com',
    measurementId: 'G-3JYE3FTBL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbu3_Th8h6bZHx6fkxfki1Ajb3wPJZ7vs',
    appId: '1:163218598684:android:fb83671b0ea8fa782928d9',
    messagingSenderId: '163218598684',
    projectId: 'memee-dev-d104d',
    storageBucket: 'memee-dev-d104d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwHaQ6jqnOOwC6TmbLNOsGpO5CCkehE4',
    appId: '1:163218598684:ios:b90a1c61e80ba37a2928d9',
    messagingSenderId: '163218598684',
    projectId: 'memee-dev-d104d',
    storageBucket: 'memee-dev-d104d.appspot.com',
    iosBundleId: 'com.memee.admin.memeeAdmin',
  );
}
