// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tcjUVP82YKmxA9q7UpQy3uTog9wb-84',
    appId: '1:999577280350:web:f4bb059ceeb151473f39cf',
    messagingSenderId: '999577280350',
    projectId: 'memee-v2',
    authDomain: 'memee-v2.firebaseapp.com',
    storageBucket: 'memee-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YzEd4dWx01dOjIYK-RwshjreC52jgUE',
    appId: '1:999577280350:android:7b922aba5e4b31933f39cf',
    messagingSenderId: '999577280350',
    projectId: 'memee-v2',
    storageBucket: 'memee-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDnV8_JX4y4BL5C9UKMh7ic-R3v84DYA',
    appId: '1:999577280350:ios:4aefc5f0058310513f39cf',
    messagingSenderId: '999577280350',
    projectId: 'memee-v2',
    storageBucket: 'memee-v2.appspot.com',
    iosBundleId: 'com.memee.admin.memeeAdmin',
  );
}
